"""initial schema

Revision ID: cc6d8af7c933
Revises: 
Create Date: 2026-09-08 23:57:00.816072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc6d8af7c933'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('vaccination', 'hygiene', 'quarantine', 'nutrition', 'biosecurity', 'general_observation', name='education_category'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', name='language'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.Enum('farmer', 'veterinarian', 'all', name='education_audience'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_content_category'), 'education_content', ['category'], unique=False)
    op.create_index(op.f('ix_education_content_language'), 'education_content', ['language'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('village', sa.String(length=150), nullable=True),
    sa.Column('district', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('farmer', 'veterinarian', 'admin', name='user_role'), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', name='language'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('animals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('species', sa.Enum('cattle', 'buffalo', name='species'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'sold', 'deceased', name='animal_status'), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'tag_id', name='uq_animal_farm_tag')
    )
    op.create_index(op.f('ix_animals_farm_id'), 'animals', ['farm_id'], unique=False)
    op.create_index(op.f('ix_animals_tag_id'), 'animals', ['tag_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('farm_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'veterinarian', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'user_id', name='uq_farm_membership')
    )
    op.create_index(op.f('ix_farm_memberships_farm_id'), 'farm_memberships', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_memberships_user_id'), 'farm_memberships', ['user_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appetite', sa.Enum('normal', 'reduced', 'none', name='appetite_level'), nullable=False),
    sa.Column('activity', sa.Enum('normal', 'reduced', 'lethargic', name='activity_level'), nullable=False),
    sa.Column('water_intake', sa.Enum('normal', 'reduced', 'increased', name='water_intake_level'), nullable=False),
    sa.Column('respiratory_sign', sa.Enum('none', 'mild', 'labored', 'coughing', name='respiratory_sign'), nullable=False),
    sa.Column('dung_sign', sa.Enum('normal', 'loose', 'diarrhea', 'bloody', name='dung_sign'), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('milk_yield_change_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('entered_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_animal_id'), 'observations', ['animal_id'], unique=False)
    op.create_index(
        'ix_observations_animal_id_observed_at',
        'observations',
        ['animal_id', sa.text('observed_at DESC')],
        unique=False,
    )
    op.create_table('vaccination_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=150), nullable=False),
    sa.Column('dose_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('administered_by', sa.String(length=36), nullable=True),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_records_animal_id'), 'vaccination_records', ['animal_id'], unique=False)
    op.create_index(op.f('ix_vaccination_records_due_date'), 'vaccination_records', ['due_date'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.Enum('low', 'medium', 'high', name='risk_band'), nullable=False),
    sa.Column('top_factors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_observation_id'), 'risk_assessments', ['observation_id'], unique=True)
    op.create_index(op.f('ix_risk_assessments_risk_band'), 'risk_assessments', ['risk_band'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='alert_priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'assigned', 'in_review', 'resolved', name='alert_status'), nullable=False),
    sa.Column('assigned_vet_id', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_vet_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_assessment_id'), 'alerts', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_alerts_assigned_vet_id'), 'alerts', ['assigned_vet_id'], unique=False)
    op.create_index(op.f('ix_alerts_priority'), 'alerts', ['priority'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(
        'ix_alerts_status_priority_created_at',
        'alerts',
        ['status', 'priority', 'created_at'],
        unique=False,
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'follow_up', 'resolved', 'ruled_out', name='case_status'), nullable=False),
    sa.Column('suspected_condition', sa.String(length=200), nullable=True),
    sa.Column('confirmed_condition', sa.String(length=200), nullable=True),
    sa.Column('confirmation_basis', sa.Text(), nullable=True),
    sa.Column('opened_by', sa.String(length=36), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_cases_animal_id'), 'cases', ['animal_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(
        'ix_cases_animal_id_status',
        'cases',
        ['animal_id', 'status'],
        unique=False,
    )
    op.create_table('case_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_updates_case_id'), 'case_updates', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_updates_case_id'), table_name='case_updates')
    op.drop_table('case_updates')
    op.drop_index('ix_cases_animal_id_status', table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_animal_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_alerts_status_priority_created_at', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_priority'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assigned_vet_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assessment_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_risk_assessments_risk_band'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_observation_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_vaccination_records_due_date'), table_name='vaccination_records')
    op.drop_index(op.f('ix_vaccination_records_animal_id'), table_name='vaccination_records')
    op.drop_table('vaccination_records')
    op.drop_index('ix_observations_animal_id_observed_at', table_name='observations')
    op.drop_index(op.f('ix_observations_animal_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_farm_memberships_user_id'), table_name='farm_memberships')
    op.drop_index(op.f('ix_farm_memberships_farm_id'), table_name='farm_memberships')
    op.drop_table('farm_memberships')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_animals_tag_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_farm_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('farms')
    op.drop_index(op.f('ix_education_content_language'), table_name='education_content')
    op.drop_index(op.f('ix_education_content_category'), table_name='education_content')
    op.drop_table('education_content')
    # ### end Alembic commands ###
